version: 2
jobs:
  build:
    docker:
      - image: node
    steps:
      - run: |
          apt -y update --fix-missing
          apt -y upgrade
          apt -y install inkscape rake
          npm install --global codecov
      - checkout
      - run: rake deps
      - run: rake build
      - run: rake lint
      - run: |
          rake test
          codecov
